# k8s-orya-chart/templates/webhook-service.yaml
{{- if and .Values.webhook.enabled .Values.webhook.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-orya.fullname" . }}-webhook-svc # Nome do serviço do webhook
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8s-orya.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  selector:
    {{- include "k8s-orya.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  ports:
    - port: {{ .Values.webhook.service.tlsPort }}
      targetPort: {{ .Values.webhook.service.targetPort }}
  type: {{ .Values.webhook.service.type }}
{{- end }}
