package pkg

const (
	ORYA_DOMAIN                                = "https://msapi.orya.tech"
	ORYA_AGENT_PORT                            = "12012"
	ORYA_NAMESPACE                             = "orya-agent"
	ORYA_CONFIG_MAP_STATE_NAME                 = "orya-state-config-map"
	ORYA_CONFIG_MAP_CONFIGURATIONS_NAME        = "orya-configurations-config-map"
	ORYA_MUTATING_WEBHOOK_NAME                 = "agent-mutate"
	ORYA_CLUSTER_ROLE_NAME                     = "k8s-orya-svc-ac-role"
	ORYA_CLUSTER_ROLE_BINDING_NAME             = "k8s-orya-svc-ac-binding"
	ORYA_DEPLOYMENT_MANAGER_NAME               = "k8s-manager"
	ORYA_DEPLOYMENT_AGENT_NAME                 = "k8s-agent"
	ORYA_DEPLOYMENT_WEBHOOK_NAME               = "k8s-webhook"
	ORYA_DEPLOYMENT_UPDATER_NAME               = "k8s-updater"
	CONTAINER_MANAGER_NAME                     = "manager"
	CONTAINER_AGENT_NAME                       = "agent"
	CONTAINER_WEBHOOK_NAME                     = "webhook"
	SERVICE_ACCOUNT_NAME                       = "k8s-orya-svc-ac"
	ORYA_REPOSITORY_IMAGE_NAME                 = "public.ecr.aws/y2o5s4q6"
	ORYA_HELM_REPOSITORY                       = "https://docp-agent.s3.us-east-1.amazonaws.com"
	ORYA_HELM_REPOSITORY_NAME                  = "orya"
	ORYA_HELM_CHART_NAME                       = "k8s-orya"
	DATADOG_HELM_REPOSITORY                    = "https://helm.datadoghq.com"
	DATADOG_DEPLOYMENT_OPERATOR_NAME           = "datadog-operator"
	DATADOG_DEPLOYMENT_CLUSTER_AGENT_NAME      = "datadog-cluster-agent"
	DATADOG_DEPLOYMENT_CLUSTER_AGENT_HELM_NAME = "datadog-agent-cluster-agent"
)
